# Generated by Django 6.0.7 on 2026-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
