# Generated by Django 6.0.7 on 2026-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sosalert_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
